### ISSUE TITLE
Unable To Save Muzei Artwork

### ISSUE THREAD

**Issue by defiant91** [banasiak/MuzeiSaver#6]
I am having an issue where I am failing to save artwork after it is successful one time. The first time I save after force closing/cache clearing the app it work fine, but subsequent saves will fail with the "Unable To Save Muzei Artwork" error. I only noticed this happening in the last few days. I tried clearing data and reinstalling the app but still had the same issue. I am on Samsung S20+, Android 11. Thanks!

**Comment by defiant91** [comment]
Update: I hooked up a debugger and found the following error:

> E/DownloadService: Unable to save bitmap
    java.lang.SecurityException: Permission Denial: opening provider com.google.android.apps.docs.storagebackend.StorageBackendContentProvider from ProcessRecord{3146bcb 5058:com.banasiak.android.muzeisaver/u0a643} (pid=5058, uid=10643) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
        at android.os.Parcel.createException(Parcel.java:2369)
        at android.os.Parcel.readException(Parcel.java:2352)
        at android.os.Parcel.readException(Parcel.java:2294)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6641)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:7546)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3086)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2484)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1803)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1521)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1497)
        at com.banasiak.android.muzeisaver.download.DownloadService.saveBitmapToFile(DownloadService.kt:53)
        at com.banasiak.android.muzeisaver.download.DownloadService.downloadArtwork(DownloadService.kt:45)
        at com.banasiak.android.muzeisaver.download.DownloadService.onHandleIntent(DownloadService.kt:33)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8811)
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8654)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9342)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2820)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3539)
    Unable To Save Muzei Artwork

**Comment by defiant91** [comment]
I created a pull request with the fix. Not sure how to link it to this issue though...

**Comment by banasiak** [comment]
Thanks @defiant91. Fixed in #7
